### ISSUE TITLE
:SVNDiff fails on Windows due to backslashed file URL

### ISSUE THREAD

**Issue by kazarmy** [juneedahamed/svnj.vim#4]
After trying to run `:SVNDiff` on a file, the following error is returned. It should be `file:///.../...` instead of `file:\\\...\...`:

```
Failed  | FAILED CMD: svn: E020024: Error resolving case of 'file:\\\C:\...'
```

Debugging the svnj.vim plugin (commit 0f2df8a84e8c2f046e3db140a1f0eb7b789dbc52) reveals that the culprit is the `expand()` call in `svnj#utils#expand()`. On Windows with [gVim 7.4.11](http://sourceforge.net/projects/cream/files/Vim/7.4.711/), it has the unfortunate and apparently undocumented behavior of turning forward slashes in file URLs into backslashes (by the way, can `expand()` be used for file URLs in the first place?).

Thus, I propose the following patch for `svnj#utils#expand()`:

```VimL
fun! svnj#utils#expand(path) "{{{2
    let path = expand(a:path)
    if has('win32') | let path = substitute(path, '\\', '/', 'g') | en
    retu  path == ""? a:path : path
endf
"2}}}
```

The patch is solely contained in the second line(`if ...`). It reverses the previously stated `expand()` behavior. Its effect is confined only to Windows and if a future `expand()` leaves forward slashes alone, the `substitute()` will have no effect.

What do you think?

**Comment by juneedahamed** [comment]
Hello Azhar

  thanks for reporting the issue, my apologies for not responding earlier. i was looking for an windows m/c but still no luck. i will try another day or two to see if any friend can spare me for a few hours else will commit those changes as you had suggested 

for the question if expand can be used for file urls. the documentation states that if the expansion fails an empty response will be returned. as you can see i return back the input as is if the returned value due to expand was empty.  i do not wanted to make decision on to call it or not from the caller based on the context maybe being lazy there to maintain it :)

Well thanks again will write to you soon if i commit any changes with/without testing (depends on windows m/c availability) and will request you to test if its acceptable 

Regards
juneed ahamed

**Comment by juneedahamed** [comment]
Hi,

  Just pushed the changes that you recommended

Regards 
Juneed

**Comment by kazarmy** [comment]
Thanks! More issues are inbound, hopefully with good patches!
